### ISSUE TITLE
[BUG] - Tensorflow not working on the GPU instance

### ISSUE THREAD

**Issue by aktech** [Quansight/qhub#1378]
### OS system and architecture in which you are running QHub

Cloud

### Expected behavior

Tensorflow detecting GPUs

### Actual behavior

Tensorflow not detecting GPUs

### How to Reproduce the problem?

```python
import tensorflow as tf
tf.__version__
tf.config.list_physical_devices()
```

* Conda Environment

```yaml
name: tf_test4
channels:
  - conda-forge
dependencies:
  - tensorflow-gpu==2.6.2
  - tensorflow==2.6.2
  - ipykernel
  - cudatoolkit
  - python==3.9.5
  - cudnn
```

### Command output

```bash session
2022-07-26 02:57:22.847459: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64
2022-07-26 02:57:22.847513: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-07-26 02:57:22.847533: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: jupyter-aktech
2022-07-26 02:57:22.847541: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: jupyter-aktech
2022-07-26 02:57:22.847623: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
2022-07-26 02:57:22.847663: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 470.57.2
```

### Versions and dependencies used.

```
$ conda --version
conda 4.10.3
```

```
kubernetes_version: '1.22'
```

```
qhub_version: 0.5.0.dev3+g4da0147
```

### Compute environment

AWS

### Anything else?

Given that nvidia-smi is detected in the instance:

```bash
02:24 $ nvidia-smi
Tue Jul 26 02:24:10 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: N/A      |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   34C    P0    22W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by aktech** [comment]
This was originally reported by @tylerpotts and the fix that worked for him was by changing the base jupyterlab docker image:
>
```
FROM nvidia/cuda:11.0.3-base-ubuntu20.04
```
>...
>
> I also checked and this only adds ~70MB of image size so for me it's certainly good enough. I dropped this new image into AWS ECR so qhub can access it, and things are working

**Comment by viniciusdc** [comment]
@aktech I think I tried that as well a while ago but still ended up with errors. We might need someone to test this again.

**Comment by aktech** [comment]
>  @aktech I think I tried that as well a while ago but still ended up with errors. Have that worked for you?


I haven't tried that yet, but it worked for Tyler. I am trying to see where the fundamental problem is, I am unable to find nvidia drivers either.

**Comment by aktech** [comment]
This can be closed now, this is fixed by using the official gpu docker images, we build now:

```yaml
default_images:
  jupyterhub: quay.io/nebari/nebari-jupyterhub:sha-f791781
  jupyterlab: quay.io/nebari/nebari-jupyterlab-gpu:sha-f791781
  dask_worker: quay.io/nebari/nebari-dask-worker-gpu:sha-f791781
```
